apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnetapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dotnetapp
  template:
    metadata:
      labels:
        app: dotnetapp
    spec:
      containers:
        - name: dotnetapp
          image: helloacr0403.azurecr.io/dotnet-app:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dotnetapp-service
spec:
  selector:
    app: dotnetapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
